### ISSUE TITLE
Pull request: feature enhancement

### ISSUE THREAD

**Issue by aleung** [osmlab/osm-deep-history#14]
I've made some improvement on this project to add features:

Common:

- Improve map UI and fix issues
- When mouse hover on table cell, highlight corresponding version of object on map and pan to center
- In table, show version which is invisible in red (removed)
- Base map layer: OpenStreetMap and Google Satellite
- Export full data of specific version in Level0L format

Node:

- Show lat, lon in table
- Show way(s) which the node belongs to

Way:

- Show history versions of way on map

@iandees 
I would like to contribute my change back to this project. But the changes are big, I don't know if all these are align with your plan on the project. The source code has been rewritten a lot with ES6, Promise and functional style. (It's supported by most of modern browsers.) So I hesitate to raise a PR. Would you like to have a look first? 

Code and readme: https://github.com/aleung/osm-deep-history

Example: 
* [Node](https://aleung.github.io/osm-deep-history/#/node/4857559003)
* [Way](https://aleung.github.io/osm-deep-history/#/way/333067739) (The map needs a few seconds to load)

**Comment by iandees** [comment]
Your code looks really interesting. I think it'd be great to have it merged in, but I also want to be thoughtful of how much load this sort of thing applies on the OSM API server. I wonder if it would make sense to only do the intensive work of loading history after clicking a button or something.

**Comment by aleung** [comment]
I have concern on the number of API calls as well. I investigated OSM API v0.6 and Overpass API, not found an approach to retrieve full history with few API calls.

I've updated to make way history only loaded on click a button "Show More on Map".

**Comment by aleung** [comment]
Close by #16
