### ISSUE TITLE
Right click>Paste doesn't work if box is empty

### ISSUE THREAD

**Issue by DaveF63** [osmlab/osm-deep-history#18]
Hi
<bit quiet around here, isn't it?>

I'm unable to right click & paste the id number into the box if it is empty. If there's is a number & I 'select all' I can do this.
Ctrl V works as expected.

**Comment by iandees** [comment]
I'm not able to reproduce this. Can you try again on the more recent version of the website? If it still doesn't work, can you let me know what browser and OS you're trying it with?
