### ISSUE TITLE
Include geometries for different versions on a map

### ISSUE THREAD

**Issue by iandees** [osmlab/osm-deep-history#2]
This is already there for node deep-history, but for ways it becomes quite a bit more complicated. We need some way of showing what a way looks like between each way version (because nodes can move without the way changing version).

I was thinking a timeline under the map with a point for each geometry change?

Also have to figure out how to handle the possibly long delay as the browser loads the history for each object.

This should probably not be done for relations quite yet.

**Comment by neogeomat** [comment]
This is what we need.

**Comment by iandees** [comment]
This is done in the more recent refactoring of the app.
