### ISSUE TITLE
Unclear map interface (objects without labels/indicators)

### ISSUE THREAD

**Issue by d1g** [osmlab/osm-deep-history#7]
http://osmlab.github.io/osm-deep-history/#/node/1 - why 5 nodes displayed at map? If they mean first node position, then please also show associated version No.

There 13 versions, why here only 5 nodes? Which is first, which is latest on map?

Good tool otherwise

**Comment by aleung** [comment]
@d1g Check my updated version: https://aleung.github.io/osm-deep-history/#/node/1

I'll raise PR to contribute back.

**Comment by aleung** [comment]
It's fixed in v1.0. This issue can be closed.
